# serverless.yml
service: serverless-flask
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128
# These are the plugins you have installed to support WSGI and pip
# requirements
plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-apigwy-binary
custom:
  wsgi:
    app: app.app
    packRequirements: false
functions:
  app:
    handler: wsgi_handler.handler
    events: # All events associated with this function
      - http:
          integration: lambda
          path: groups/{id}
          method: get
          contentHandling: CONVERT_TO_BINARY