# serverless.yml

service: zootle-serverless

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  customDomains:
    - rest:
        domainName: zootle.me
        stage: prod
        basePath:
        certificateName: 'zootle.me'
        createRoute53Record: true
        endpointType: 'regional'
    - rest:
        domainName: www.zootle.me
        stage: prod
        basePath:
        certificateName: 'zootle.me'
        createRoute53Record: true
        endpointType: 'regional'



provider:
  name: aws
  runtime: python3.8
  stage: prod
  timeout: 45
  region: us-east-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

